### PR TITLE
Update to better-sqlite3 version 7.4.4

### PR DESCRIPTION
**Pull request by Wambou**
Hi,

_better-sqlite3_ released a version a few days ago that provide support for electron 14 and 15.

Since I need the support, I checked the changes and picked them for this repo.

I hope you will be able to quickly generate a version :)

### CODE REVIEW

**Comment by m4heshd** [comment]
Hi @Wambou,
Yes I was aware of the new release but I kept it on hold for a while because of two reasons.

1. Prebuilds were having a lot of trouble because of `prebuild-install` (don't know if it's solved yet)
2. I hardly had any time to run necessary tests

So thank you for doing the work for me. But I see that you haven't tested the workflow runs on your fork. Could you trigger them and see if they succeed?

**Review by m4heshd — APPROVED** [review]
Pre-approving till the workflow success confirmation.

**Comment by m4heshd** [comment]
> prebuild info build Uploading 4 prebuilds(s) to GitHub releases
> prebuild ERR! build Error: Error from GitHub: Not Found

Oh this is because you triggered it manually. There's no release for the upload to complete. You have to create a tag in the final commit and create a release to properly trigger the workflow.

**Comment by Wambou** [comment]
I created it through GitHub, I will do it locally then push, to see if it works better.
Thanks for the information

**Comment by Wambou** [comment]
There is something that I must miss somewhere...

I created the tag manually and push it, then created the release and wait for the workflow to finish, I still get the following error (fully detailed at the end):
> [...]
> prebuild info build Prebuild written to prebuilds/better-sqlite3-multiple-ciphers-v7.4.4-node-v93-linux-x64.tar.gz
> prebuild info build Uploading 4 prebuilds(s) to GitHub releases
> prebuild ERR! build Error: Error from GitHub: Not Found
> [...]

So I tried to create a release for version `v7.4.3`, that worked properly with these logs at the end:
> [...]
> prebuild info build Prebuild written to prebuilds\better-sqlite3-multiple-ciphers-v7.4.3-node-v93-win32-x64.tar.gz
> prebuild info build Uploading 4 prebuilds(s) to GitHub releases
> prebuild info build Found 24 prebuild(s) on Github
> prebuild info build -> better-sqlite3-multiple-ciphers-v7.4.3-electron-v82-darwin-x64.tar.gz
> [...]

The problem seems to be that there is no pre-existing prebuild on GitHub, which does not make a lot of sense, since I want to create it.
I created the release using the same name as the tag and the version in `package.json`, where before I was trying to create a version called `v7.4.4-r.c1` to avoid polluting the real release to come.

I am new to the workflow feature, but why the `v7.4.3` version works but not the `v7.4.4` ?
I will try to explore a bit more the error from `ghutils` later on (see below), but if you have some insight, I am all ears.

=========

The full error:
> prebuild ERR! build Error: Error from GitHub: Not Found
> prebuild ERR! build     at createError (/home/runner/work/better-sqlite3-multiple-ciphers/better-sqlite3-multiple-ciphers/node_modules/ghutils/ghutils.js:36:10)
> prebuild ERR! build     at responseHandler (/home/runner/work/better-sqlite3-multiple-ciphers/better-sqlite3-multiple-ciphers/node_modules/ghutils/ghutils.js:26:23)
> prebuild ERR! build     at BufferList._callback (/home/runner/work/better-sqlite3-multiple-ciphers/better-sqlite3-multiple-ciphers/node_modules/jsonist/jsonist.js:61:7)
> prebuild ERR! build     at BufferList.end (/home/runner/work/better-sqlite3-multiple-ciphers/better-sqlite3-multiple-ciphers/node_modules/bl/bl.js:113:10)
> prebuild ERR! build     at DestroyableTransform.onend (/home/runner/work/better-sqlite3-multiple-ciphers/better-sqlite3-multiple-ciphers/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
> prebuild ERR! build     at Object.onceWrapper (node:events:509:28)
> prebuild ERR! build     at DestroyableTransform.emit (node:events:402:35)
> prebuild ERR! build     at /home/runner/work/better-sqlite3-multiple-ciphers/better-sqlite3-multiple-ciphers/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
> prebuild ERR! build     at processTicksAndRejections (node:internal/process/task_queues:78:11)
> Error: Process completed with exit code 2.

**Comment by m4heshd** [comment]
Oh. Now the issue is `prebuild` considering the `repository` field from `package.json` which at the moment is original repo and not your fork. When It's trying to upload, two issues occur,

1. Original repo doesn't have that particular tag (hence the error)
2. The CLI won't have authorization to the original repo when running in your fork

This is why I mentioned I didn't have the time for tests because it's an absolute pain testing workflows without polluting the commit flow and spamming releases. For this reason, I'm using another mirror of this repo just for workflow tests.

Also looking at your recent runs, the `alpine` build is failing just as I suspected. I might have to look into that too.

**Comment by Wambou** [comment]
> [...] the `repository` field from `package.json` which at the moment is original repo and not your fork.

Now it makes total sense once you said it...
Once it’s fixed, all is good 😄 

> Also looking at your recent runs, the `alpine` build is failing just as I suspected. I might have to look into that too.

From what I saw, the error was the same as with other builds.
Now that I changed the repository URL, it seems to work perfectly.
Let me revert back the last commit and the PR will be ready to be merged.

> This is why I mentioned I didn't have the time for tests because it's an absolute pain testing workflows without polluting the commit flow and spamming releases. For this reason, I'm using another mirror of this repo just for workflow tests.

Good to know.
Thank you for your help so that I can conduct the tests.

> I'll be writing another dev workflow as soon as I get some time on my hand which will make the build testing a bit less painful.

Now that I got some insight on how it works, if you want some help I might be able to try to write one.
The problem I see is that the action is only triggered for a release.
Maybe a commit on a specific testing branch could trigger the workflow too, at least the build part and running unit tests.

**Comment by m4heshd** [comment]
> From what I saw, the error was the same as with other builds.

Huh, that's weird. 🤔 When I checked the failed run before it was a bindings error in compilation.

> Maybe a commit on a specific testing branch could trigger the workflow too

I'll be writing it to be triggered manually. I've already written a workflow for another project which is very similar. Just need a little time.

All in all, good work. Merging.

**Comment by Wambou** [comment]
Thank you for merging it quickly !
And for your knowledge about workflows that helped me test it things.

**Pull request merged**
